In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_openml
import ssl
import certifi

ssl._create_default_https_context = ssl._create_unverified_context
dataset = fetch_openml(data_id=327, as_frame=True)

In [29]:
df = dataset.frame
df2 = df.set_index('LOCATION')

In [30]:
df.head(20)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,M,3,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,A,25,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,A,29,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,M,23,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
5,A,27,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,M,3,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
9,A,29,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
10,A,39,1853.0,RR,NaN,2.0,N,DECK,WOOD,NaN,S,WOOD
11,M,6,1856.0,HIGHWAY,1200.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
12,A,33,1856.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
13,A,28,1857.0,RR,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
14,A,25,1859.0,HIGHWAY,1030.0,2.0,N,THROUGH,IRON,MEDIUM,S-F,SUSPEN
15,M,4,1863.0,RR,1000.0,2.0,N,THROUGH,IRON,MEDIUM,NaN,SIMPLE-T
16,A,28,1864.0,RR,1200.0,2.0,N,THROUGH,IRON,SHORT,S,SIMPLE-T
17,A,29,1866.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
18,A,32,1870.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
19,M,16,1874.0,RR,NaN,2.0,NaN,THROUGH,IRON,NaN,NaN,SIMPLE-T

In [31]:
df2.head()

,RIVER,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
LOCATION,,,,,,,,,,,
3,M,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
25,A,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
39,A,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
29,A,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
23,M,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD

In [32]:
result = df2.loc['39']
type(result)

pandas.core.frame.DataFrame

In [6]:
result = df2.iloc[2]
print(result)

RIVER              A
ERECTED       1829.0
PURPOSE     AQUEDUCT
LENGTH           NaN
LANES            1.0
CLEAR-G            N
T-OR-D       THROUGH
MATERIAL        WOOD
SPAN             NaN
REL-L              S
TYPE            WOOD
Name: 39, dtype: object

In [33]:
df2.reset_index(inplace=True)
df2.head(20)

,LOCATION,RIVER,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,3,M,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,25,A,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,39,A,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,29,A,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,23,M,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
5,27,A,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,28,A,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,3,M,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,39,A,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
9,29,A,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
10,39,A,1853.0,RR,NaN,2.0,N,DECK,WOOD,NaN,S,WOOD
11,6,M,1856.0,HIGHWAY,1200.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
12,33,A,1856.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
13,28,A,1857.0,RR,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
14,25,A,1859.0,HIGHWAY,1030.0,2.0,N,THROUGH,IRON,MEDIUM,S-F,SUSPEN
15,4,M,1863.0,RR,1000.0,2.0,N,THROUGH,IRON,MEDIUM,NaN,SIMPLE-T
16,28,A,1864.0,RR,1200.0,2.0,N,THROUGH,IRON,SHORT,S,SIMPLE-T
17,29,A,1866.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
18,32,A,1870.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
19,16,M,1874.0,RR,NaN,2.0,NaN,THROUGH,IRON,NaN,NaN,SIMPLE-T

In [8]:
df['MATERIAL'].value_counts()

STEEL    78
WOOD     16
IRON     11
Name: MATERIAL, dtype: int64

In [34]:
cond = df['MATERIAL'] == 'WOOD'
df2 = df[cond]

df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,M,3,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,A,25,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,A,29,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,M,23,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
5,A,27,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
9,A,29,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
10,A,39,1853.0,RR,NaN,2.0,N,DECK,WOOD,NaN,S,WOOD
11,M,6,1856.0,HIGHWAY,1200.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
12,A,33,1856.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
13,A,28,1857.0,RR,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
17,A,29,1866.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
18,A,32,1870.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
21,A,24,1876.0,HIGHWAY,1200.0,4.0,G,THROUGH,WOOD,SHORT,S,WOOD
38,A,27,1892.0,AQUEDUCT,1092.0,1.0,N,THROUGH,WOOD,SHORT,S,WOOD

In [35]:
df2 = df[df['MATERIAL'] == 'IRON']
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,M,3,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
14,A,25,1859.0,HIGHWAY,1030.0,2.0,N,THROUGH,IRON,MEDIUM,S-F,SUSPEN
15,M,4,1863.0,RR,1000.0,2.0,N,THROUGH,IRON,MEDIUM,NaN,SIMPLE-T
16,A,28,1864.0,RR,1200.0,2.0,N,THROUGH,IRON,SHORT,S,SIMPLE-T
19,M,16,1874.0,RR,NaN,2.0,NaN,THROUGH,IRON,NaN,NaN,SIMPLE-T
29,A,30,1887.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
32,M,19,1889.0,HIGHWAY,1120.0,NaN,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
33,O,45,1890.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,SHORT,F,SIMPLE-T
35,M,17,1891.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
40,M,11,1894.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T

In [11]:
df2 = df[(df['MATERIAL'] == 'IRON') & (df['LENGTH'] >= 1100) ]
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
7,M,3,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
16,A,28,1864.0,RR,1200.0,2.0,N,THROUGH,IRON,SHORT,S,SIMPLE-T
32,M,19,1889.0,HIGHWAY,1120.0,NaN,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T

In [12]:
#df2 = df[(df['LENGTH'] >= 500) & (df['LENGTH'] <= 1000)]

df2 = df[df['LENGTH'].between(500, 1000)]
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
3,A,29,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
5,A,27,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
9,A,29,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
15,M,4,1863.0,RR,1000.0,2.0,N,THROUGH,IRON,MEDIUM,NaN,SIMPLE-T
17,A,29,1866.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
18,A,32,1870.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
28,M,3,1884.0,HIGHWAY,1000.0,2.0,G,THROUGH,STEEL,MEDIUM,S,ARCH
34,A,27,1890.0,HIGHWAY,1000.0,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
56,A,28,1904.0,RR,965.0,4.0,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
65,A,24,1915.0,HIGHWAY,1000.0,4.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
69,A,29,1923.0,HIGHWAY,885.0,4.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
71,A,27,1926.0,HIGHWAY,860.0,4.0,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
72,A,26,1926.0,HIGHWAY,884.0,4.0,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
79,A,25,1928.0,HIGHWAY,860.0,4.0,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
87,A,39.7,1945.0,RR,840.0,2.0,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
93,M,22,1951.0,HIGHWAY,900.0,4.0,G,THROUGH,STEEL,MEDIUM,F,CONT-T
97,O,42,1955.0,HIGHWAY,804.0,NaN,G,THROUGH,STEEL,NaN,F,SIMPLE-T
99,M,1,1959.0,HIGHWAY,1000.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
100,A,33,1961.0,HIGHWAY,980.0,4.0,G,DECK,STEEL,MEDIUM,S-F,CONT-T
102,A,24,1969.0,HIGHWAY,870.0,6.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
104,M,7,1978.0,HIGHWAY,950.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH

In [13]:
df['PURPOSE'].value_counts()

HIGHWAY     69
RR          31
AQUEDUCT     4
WALK         1
Name: PURPOSE, dtype: int64

In [14]:
df2 = df[df['PURPOSE'].isin(['AQUEDUCT', 'WALK'])]
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
38,A,27,1892.0,AQUEDUCT,1092.0,1.0,N,THROUGH,WOOD,SHORT,S,WOOD
68,A,30,1921.0,WALK,NaN,NaN,G,THROUGH,STEEL,NaN,F,SUSPEN

In [15]:
df2 = df[df.isnull().any(axis=1)]
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,M,3,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
4,M,23,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
10,A,39,1853.0,RR,NaN,2.0,N,DECK,WOOD,NaN,S,WOOD
12,A,33,1856.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
13,A,28,1857.0,RR,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
15,M,4,1863.0,RR,1000.0,2.0,N,THROUGH,IRON,MEDIUM,NaN,SIMPLE-T
19,M,16,1874.0,RR,NaN,2.0,NaN,THROUGH,IRON,NaN,NaN,SIMPLE-T
20,M,1,1876.0,HIGHWAY,1245.0,NaN,NaN,THROUGH,STEEL,LONG,F,SUSPEN
22,O,45,1878.0,RR,NaN,2.0,G,NaN,STEEL,NaN,NaN,SIMPLE-T
23,M,10,1882.0,RR,NaN,2.0,G,NaN,STEEL,NaN,NaN,SIMPLE-T
24,A,39,1883.0,RR,NaN,2.0,G,THROUGH,STEEL,NaN,F,SIMPLE-T
26,A,31,1884.0,RR,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
27,A,26,1884.0,HIGHWAY,1080.0,2.0,G,THROUGH,STEEL,MEDIUM,NaN,SUSPEN
29,A,30,1887.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
32,M,19,1889.0,HIGHWAY,1120.0,NaN,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
33,O,45,1890.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,SHORT,F,SIMPLE-T
35,M,17,1891.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
37,A,25,1892.0,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
39,M,22,1893.0,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
40,M,11,1894.0,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
42,O,48,1896.0,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,LONG,F,SUSPEN
45,M,14,1897.0,RR,2264.0,NaN,G,THROUGH,STEEL,NaN,F,SIMPLE-T
49,M,13,1901.0,RR,NaN,2.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
54,M,21,1903.0,RR,1154.0,NaN,G,THROUGH,STEEL,LONG,F,SIMPLE-T
57,M,2,1904.0,RR,1504.0,NaN,G,THROUGH,STEEL,LONG,F,CANTILEV
58,Y,NaN,1908.0,HIGHWAY,1240.0,NaN,G,NaN,STEEL,MEDIUM,F,SIMPLE-T
59,M,23,1909.0,HIGHWAY,NaN,NaN,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
63,M,10,1914.0,RR,2210.0,NaN,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
68,A,30,1921.0,WALK,NaN,NaN,G,THROUGH,STEEL,NaN,F,SUSPEN
74,A,38,1927.0,HIGHWAY,1508.0,NaN,G,THROUGH,STEEL,MEDIUM,S,ARCH
90,Y,52,1945.0,HIGHWAY,NaN,NaN,G,THROUGH,STEEL,MEDIUM,S,ARCH
91,Y,51,1945.0,RR,NaN,NaN,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
97,O,42,1955.0,HIGHWAY,804.0,NaN,G,THROUGH,STEEL,NaN,F,SIMPLE-T

In [36]:
length = 1000
df2 = df.query('MATERIAL == "WOOD" and LENGTH > @length')
df2

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
1,A,25,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
11,M,6,1856.0,HIGHWAY,1200.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
21,A,24,1876.0,HIGHWAY,1200.0,4.0,G,THROUGH,WOOD,SHORT,S,WOOD
38,A,27,1892.0,AQUEDUCT,1092.0,1.0,N,THROUGH,WOOD,SHORT,S,WOOD

In [39]:
df2 = df.groupby(['MATERIAL', 'PURPOSE'])

print(type(df2))

for name, grp in df2:
    print(f'{name}')
    print(grp)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
('WOOD', 'AQUEDUCT')
   RIVER LOCATION  ERECTED   PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
2      A       39   1829.0  AQUEDUCT     NaN    1.0       N  THROUGH     WOOD
8      A       39   1848.0  AQUEDUCT     NaN    1.0       N     DECK     WOOD
38     A       27   1892.0  AQUEDUCT  1092.0    1.0       N  THROUGH     WOOD

     SPAN REL-L  TYPE
2     NaN     S  WOOD
8     NaN     S  WOOD
38  SHORT     S  WOOD
('WOOD', 'RR')
   RIVER LOCATION  ERECTED PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
10     A       39   1853.0      RR     NaN    2.0       N     DECK     WOOD
13     A       28   1857.0      RR     NaN    2.0       N  THROUGH     WOOD

   SPAN REL-L  TYPE
10  NaN     S  WOOD
13  NaN     S  WOOD
('WOOD', 'HIGHWAY')
   RIVER LOCATION  ERECTED  PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
0      M        3   1818.0  HIGHWAY     NaN    2.0       N  THROUGH     WOOD
1      A       25   1819.0  HIGHWAY  1037.0    2.0       N  THROUGH     WOOD
3      A       29   1837.0  HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
4      M       23   1838.0  HIGHWAY     NaN    2.0       N  THROUGH     WOOD
5      A       27   1840.0  HIGHWAY   990.0    2.0       N  THROUGH     WOOD
9      A       29   1851.0  HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
11     M        6   1856.0  HIGHWAY  1200.0    2.0       N  THROUGH     WOOD
12     A       33   1856.0  HIGHWAY     NaN    2.0       N  THROUGH     WOOD
17     A       29   1866.0  HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
18     A       32   1870.0  HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
21     A       24   1876.0  HIGHWAY  1200.0    4.0       G  THROUGH     WOOD

      SPAN REL-L  TYPE
0    SHORT     S  WOOD
1    SHORT     S  WOOD
3    SHORT     S  WOOD
4      NaN     S  WOOD
5   MEDIUM     S  WOOD
9   MEDIUM     S  WOOD
11  MEDIUM     S  WOOD
12     NaN     S  WOOD
17  MEDIUM     S  WOOD
18  MEDIUM     S  WOOD
21   SHORT     S  WOOD
('IRON', 'AQUEDUCT')
  RIVER LOCATION  ERECTED   PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
6     A       28   1844.0  AQUEDUCT  1000.0    1.0       N  THROUGH     IRON

    SPAN REL-L    TYPE
6  SHORT     S  SUSPEN
('IRON', 'RR')
   RIVER LOCATION  ERECTED PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
15     M        4   1863.0      RR  1000.0    2.0       N  THROUGH     IRON
16     A       28   1864.0      RR  1200.0    2.0       N  THROUGH     IRON
19     M       16   1874.0      RR     NaN    2.0     NaN  THROUGH     IRON

      SPAN REL-L      TYPE
15  MEDIUM   NaN  SIMPLE-T
16   SHORT     S  SIMPLE-T
19     NaN   NaN  SIMPLE-T
('IRON', 'HIGHWAY')
   RIVER LOCATION  ERECTED  PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
7      M        3   1846.0  HIGHWAY  1500.0    2.0       N  THROUGH     IRON
14     A       25   1859.0  HIGHWAY  1030.0    2.0       N  THROUGH     IRON
29     A       30   1887.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
32     M       19   1889.0  HIGHWAY  1120.0    NaN       G  THROUGH     IRON
33     O       45   1890.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
35     M       17   1891.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
40     M       11   1894.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON

      SPAN REL-L      TYPE
7    SHORT     S    SUSPEN
14  MEDIUM   S-F    SUSPEN
29  MEDIUM     F  SIMPLE-T
32  MEDIUM     F  SIMPLE-T
33   SHORT     F  SIMPLE-T
35  MEDIUM     F  SIMPLE-T
40  MEDIUM     F  SIMPLE-T
('STEEL', 'WALK')
   RIVER LOCATION  ERECTED PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
68     A       30   1921.0    WALK     NaN    NaN       G  THROUGH    STEEL

   SPAN REL-L    TYPE
68  NaN     F  SUSPEN
('STEEL', 'RR')
   RIVER LOCATION  ERECTED PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
22     O       45   1878.0      RR     NaN    2.0       G      NaN    STEEL
23     M       10   1882.0      RR     NaN    2.0       G      NaN    STEEL
24     A       39   1883.0      RR     NaN    2.0       G  THROUGH    STEEL
25     M       12   1883.0      RR  1150.0    2.0       G  THROUGH    STEEL
26     A       31   1884.0      RR     NaN    2.0       G  THROUGH    STEEL
30     M        8   1887.0      RR  1161.0    2.0       G  THROUGH    STEEL
31     O       41   1888.0      RR  4558.0    2.0       G  THROUGH    STEEL
36     M       18   1891.0      RR  1350.0    2.0       G  THROUGH    STEEL
44     A       37   1897.0      RR  4000.0    2.0       G     DECK    STEEL
45     M       14   1897.0      RR  2264.0    NaN       G  THROUGH    STEEL
46     M       15   1898.0      RR  2000.0    2.0       G  THROUGH    STEEL
49     M       13   1901.0      RR     NaN    2.0       G  THROUGH    STEEL
51     M       16   1903.0      RR  1300.0    2.0       G  THROUGH    STEEL
52     A       35   1903.0      RR  3000.0    2.0       G  THROUGH    STEEL
53     M        6   1903.0      RR  1417.0    2.0       G  THROUGH    STEEL
54     M       21   1903.0      RR  1154.0    NaN       G  THROUGH    STEEL
55     M        4   1904.0      RR  1200.0    2.0       G  THROUGH    STEEL
56     A       28   1904.0      RR   965.0    4.0       G  THROUGH    STEEL
57     M        2   1904.0      RR  1504.0    NaN       G  THROUGH    STEEL
61     O       49   1910.0      RR  1620.0    2.0       G  THROUGH    STEEL
63     M       10   1914.0      RR  2210.0    NaN       G  THROUGH    STEEL
64     O       41   1915.0      RR  2822.0    2.0       G  THROUGH    STEEL
66     A       37   1918.0      RR  2300.0    2.0       N     DECK    STEEL
67     A       31   1920.0      RR  2122.0    2.0       G  THROUGH    STEEL
87     A     39.7   1945.0      RR   840.0    2.0       G  THROUGH    STEEL
91     Y       51   1945.0      RR     NaN    NaN       G  THROUGH    STEEL

      SPAN REL-L      TYPE
22     NaN   NaN  SIMPLE-T
23     NaN   NaN  SIMPLE-T
24     NaN     F  SIMPLE-T
25  MEDIUM     S  SIMPLE-T
26  MEDIUM     F  SIMPLE-T
30  MEDIUM     S  SIMPLE-T
31    LONG     F  SIMPLE-T
36  MEDIUM     S  SIMPLE-T
44    LONG     F  SIMPLE-T
45     NaN     F  SIMPLE-T
46  MEDIUM     S  SIMPLE-T
49    LONG     F  SIMPLE-T
51  MEDIUM     S  SIMPLE-T
52  MEDIUM     S  SIMPLE-T
53  MEDIUM     F  SIMPLE-T
54    LONG     F  SIMPLE-T
55  MEDIUM   S-F  SIMPLE-T
56  MEDIUM   S-F  SIMPLE-T
57    LONG     F  CANTILEV
61    LONG     F  CANTILEV
63  MEDIUM     F  SIMPLE-T
64    LONG     F  SIMPLE-T
66    LONG     F    CONT-T
67  MEDIUM     F  SIMPLE-T
87  MEDIUM   S-F  SIMPLE-T
91  MEDIUM     F  SIMPLE-T
('STEEL', 'HIGHWAY')
    RIVER LOCATION  ERECTED  PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
20      M        1   1876.0  HIGHWAY  1245.0    NaN     NaN  THROUGH    STEEL
27      A       26   1884.0  HIGHWAY  1080.0    2.0       G  THROUGH    STEEL
28      M        3   1884.0  HIGHWAY  1000.0    2.0       G  THROUGH    STEEL
34      A       27   1890.0  HIGHWAY  1000.0    2.0       G  THROUGH    STEEL
37      A       25   1892.0  HIGHWAY     NaN    2.0       G  THROUGH    STEEL
39      M       22   1893.0  HIGHWAY     NaN    2.0       G  THROUGH    STEEL
41      M        9   1895.0  HIGHWAY  2367.0    2.0       G  THROUGH    STEEL
42      O       48   1896.0  HIGHWAY     NaN    2.0       G  THROUGH    STEEL
43      M        7   1896.0  HIGHWAY  1040.0    2.0       G  THROUGH    STEEL
47      A       33   1900.0  HIGHWAY  1200.0    2.0       G  THROUGH    STEEL
48      A       38   1900.0  HIGHWAY  2000.0    2.0       G  THROUGH    STEEL
50      A       34   1902.0  HIGHWAY  1850.0    2.0       G  THROUGH    STEEL
58      Y      NaN   1908.0  HIGHWAY  1240.0    NaN       G      NaN    STEEL
59      M       23   1909.0  HIGHWAY     NaN    NaN       G  THROUGH    STEEL
60      A       36   1909.0  HIGHWAY  1730.0    2.0       G  THROUGH    STEEL
62      O       43   1911.0  HIGHWAY  1652.0    2.0       G  THROUGH    STEEL
65      A       24   1915.0  HIGHWAY  1000.0    4.0       G  THROUGH    STEEL
69      A       29   1923.0  HIGHWAY   885.0    4.0       G  THROUGH    STEEL
70      A       32   1924.0  HIGHWAY  2365.0    4.0       G  THROUGH    STEEL
71      A       27   1926.0  HIGHWAY   860.0    4.0       G  THROUGH    STEEL
72      A       26   1926.0  HIGHWAY   884.0    4.0       G  THROUGH    STEEL
73      O       46   1927.0  HIGHWAY  1770.0    2.0       G  THROUGH    STEEL
74      A       38   1927.0  HIGHWAY  1508.0    NaN       G  THROUGH    STEEL
75      M        5   1927.0  HIGHWAY  2663.0    4.0       N     DECK    STEEL
76      M        1   1927.0  HIGHWAY  1330.0    4.0       G  THROUGH    STEEL
77      A       30   1928.0  HIGHWAY  2678.0    4.0       G     DECK    STEEL
78      M       20   1928.0  HIGHWAY  2220.0    2.0       G     DECK    STEEL
79      A       25   1928.0  HIGHWAY   860.0    4.0       G  THROUGH    STEEL
80      M       17   1928.0  HIGHWAY  2250.0    2.0       G  THROUGH    STEEL
81      O       40   1931.0  HIGHWAY  1365.0    4.0       G  THROUGH    STEEL
82      O       42   1931.0  HIGHWAY  1450.0    4.0       N  THROUGH    STEEL
83      M        6   1931.0  HIGHWAY  1500.0    4.0       G  THROUGH    STEEL
84      M       11   1937.0  HIGHWAY  1690.0    4.0       N     DECK    STEEL
85      A       34   1939.0  HIGHWAY  1800.0    4.0       G     DECK    STEEL
86      A     39.5   1945.0  HIGHWAY  1060.0    4.0       G     DECK    STEEL
88      A     38.5   1945.0  HIGHWAY  1710.0    2.0       N     DECK    STEEL
89      O       48   1945.0  HIGHWAY  2160.0    2.0       G  THROUGH    STEEL
90      Y       52   1945.0  HIGHWAY     NaN    NaN       G  THROUGH    STEEL
92      M       23   1950.0  HIGHWAY  1320.0    2.0       G  THROUGH    STEEL
93      M       22   1951.0  HIGHWAY   900.0    4.0       G  THROUGH    STEEL
94      M       14   1951.0  HIGHWAY  2423.0    4.0       G     DECK    STEEL
95      M       19   1951.0  HIGHWAY  1031.0    4.0       G  THROUGH    STEEL
96      A       37   1955.0  HIGHWAY  2300.0    4.0       N     DECK    STEEL
97      O       42   1955.0  HIGHWAY   804.0    NaN       G  THROUGH    STEEL
98      O       47   1959.0  HIGHWAY  1700.0    2.0       G  THROUGH    STEEL
99      M        1   1959.0  HIGHWAY  1000.0    6.0       G  THROUGH    STEEL
100     A       33   1961.0  HIGHWAY   980.0    4.0       G     DECK    STEEL
101     M        9   1962.0  HIGHWAY  2213.0    4.0       G     DECK    STEEL
102     A       24   1969.0  HIGHWAY   870.0    6.0       G  THROUGH    STEEL
103     O       44   1975.0  HIGHWAY  3756.0    6.0       G  THROUGH    STEEL
104     M        7   1978.0  HIGHWAY   950.0    6.0       G  THROUGH    STEEL

       SPAN REL-L      TYPE
20     LONG     F    SUSPEN
27   MEDIUM   NaN    SUSPEN
28   MEDIUM     S      ARCH
34   MEDIUM     F  SIMPLE-T
37   MEDIUM     F  SIMPLE-T
39   MEDIUM     F  SIMPLE-T
41     LONG     F  SIMPLE-T
42     LONG     F    SUSPEN
43     LONG     F      ARCH
47   MEDIUM     F  SIMPLE-T
48   MEDIUM     F  SIMPLE-T
50   MEDIUM     F  CANTILEV
58   MEDIUM     F  SIMPLE-T
59   MEDIUM     F  SIMPLE-T
60     LONG     F  SIMPLE-T
62     LONG     F  CANTILEV
65     LONG     F  SIMPLE-T
69   MEDIUM     F      ARCH
70   MEDIUM     S      ARCH
71   MEDIUM   S-F    SUSPEN
72   MEDIUM   S-F    SUSPEN
73     LONG   S-F  CANTILEV
74   MEDIUM     S      ARCH
75   MEDIUM   S-F  CANTILEV
76     LONG     F  CANTILEV
77   MEDIUM     F      ARCH
78   MEDIUM   S-F  CANTILEV
79   MEDIUM   S-F    SUSPEN
80   MEDIUM     S  SIMPLE-T
81     LONG     F      ARCH
82     LONG     F      ARCH
83     LONG     F    SUSPEN
84     LONG   S-F    CONT-T
85   MEDIUM     F  CANTILEV
86   MEDIUM   S-F    CONT-T
88   MEDIUM   S-F    CONT-T
89     LONG     F  CANTILEV
90   MEDIUM     S      ARCH
92   MEDIUM   S-F  SIMPLE-T
93   MEDIUM     F    CONT-T
94     LONG     F    CONT-T
95     LONG     F  CANTILEV
96     LONG     F    CONT-T
97      NaN     F  SIMPLE-T
98     LONG     F    CONT-T
99     LONG     F      ARCH
100  MEDIUM   S-F    CONT-T
101    LONG     F    CONT-T
102  MEDIUM     F      ARCH
103    LONG     F      ARCH
104    LONG     F      ARCH

In [41]:
def style(idx):
    year = df.loc[idx, 'ERECTED']
    if year < 1870:
        return 'Classic'
    elif year < 1890:
        return 'Industrial'
    else:
        return 'Modern'
    
df2 = df.groupby(style)

for name, grp in df2:
    print(f'{name}')
    print(grp)

Classic
   RIVER LOCATION  ERECTED   PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
0      M        3   1818.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
1      A       25   1819.0   HIGHWAY  1037.0    2.0       N  THROUGH     WOOD
2      A       39   1829.0  AQUEDUCT     NaN    1.0       N  THROUGH     WOOD
3      A       29   1837.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
4      M       23   1838.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
5      A       27   1840.0   HIGHWAY   990.0    2.0       N  THROUGH     WOOD
6      A       28   1844.0  AQUEDUCT  1000.0    1.0       N  THROUGH     IRON
7      M        3   1846.0   HIGHWAY  1500.0    2.0       N  THROUGH     IRON
8      A       39   1848.0  AQUEDUCT     NaN    1.0       N     DECK     WOOD
9      A       29   1851.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
10     A       39   1853.0        RR     NaN    2.0       N     DECK     WOOD
11     M        6   1856.0   HIGHWAY  1200.0    2.0       N  THROUGH     WOOD
12     A       33   1856.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
13     A       28   1857.0        RR     NaN    2.0       N  THROUGH     WOOD
14     A       25   1859.0   HIGHWAY  1030.0    2.0       N  THROUGH     IRON
15     M        4   1863.0        RR  1000.0    2.0       N  THROUGH     IRON
16     A       28   1864.0        RR  1200.0    2.0       N  THROUGH     IRON
17     A       29   1866.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD

      SPAN REL-L      TYPE
0    SHORT     S      WOOD
1    SHORT     S      WOOD
2      NaN     S      WOOD
3    SHORT     S      WOOD
4      NaN     S      WOOD
5   MEDIUM     S      WOOD
6    SHORT     S    SUSPEN
7    SHORT     S    SUSPEN
8      NaN     S      WOOD
9   MEDIUM     S      WOOD
10     NaN     S      WOOD
11  MEDIUM     S      WOOD
12     NaN     S      WOOD
13     NaN     S      WOOD
14  MEDIUM   S-F    SUSPEN
15  MEDIUM   NaN  SIMPLE-T
16   SHORT     S  SIMPLE-T
17  MEDIUM     S      WOOD
Industrial
   RIVER LOCATION  ERECTED  PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
18     A       32   1870.0  HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
19     M       16   1874.0       RR     NaN    2.0     NaN  THROUGH     IRON
20     M        1   1876.0  HIGHWAY  1245.0    NaN     NaN  THROUGH    STEEL
21     A       24   1876.0  HIGHWAY  1200.0    4.0       G  THROUGH     WOOD
22     O       45   1878.0       RR     NaN    2.0       G      NaN    STEEL
23     M       10   1882.0       RR     NaN    2.0       G      NaN    STEEL
24     A       39   1883.0       RR     NaN    2.0       G  THROUGH    STEEL
25     M       12   1883.0       RR  1150.0    2.0       G  THROUGH    STEEL
26     A       31   1884.0       RR     NaN    2.0       G  THROUGH    STEEL
27     A       26   1884.0  HIGHWAY  1080.0    2.0       G  THROUGH    STEEL
28     M        3   1884.0  HIGHWAY  1000.0    2.0       G  THROUGH    STEEL
29     A       30   1887.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
30     M        8   1887.0       RR  1161.0    2.0       G  THROUGH    STEEL
31     O       41   1888.0       RR  4558.0    2.0       G  THROUGH    STEEL
32     M       19   1889.0  HIGHWAY  1120.0    NaN       G  THROUGH     IRON

      SPAN REL-L      TYPE
18  MEDIUM     S      WOOD
19     NaN   NaN  SIMPLE-T
20    LONG     F    SUSPEN
21   SHORT     S      WOOD
22     NaN   NaN  SIMPLE-T
23     NaN   NaN  SIMPLE-T
24     NaN     F  SIMPLE-T
25  MEDIUM     S  SIMPLE-T
26  MEDIUM     F  SIMPLE-T
27  MEDIUM   NaN    SUSPEN
28  MEDIUM     S      ARCH
29  MEDIUM     F  SIMPLE-T
30  MEDIUM     S  SIMPLE-T
31    LONG     F  SIMPLE-T
32  MEDIUM     F  SIMPLE-T
Modern
    RIVER LOCATION  ERECTED  PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
33      O       45   1890.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
34      A       27   1890.0  HIGHWAY  1000.0    2.0       G  THROUGH    STEEL
35      M       17   1891.0  HIGHWAY     NaN    2.0       G  THROUGH     IRON
36      M       18   1891.0       RR  1350.0    2.0       G  THROUGH    STEEL
37      A       25   1892.0  HIGHWAY     NaN    2.0       G  THROUGH    STEEL
..    ...      ...      ...      ...     ...    ...     ...      ...      ...
100     A       33   1961.0  HIGHWAY   980.0    4.0       G     DECK    STEEL
101     M        9   1962.0  HIGHWAY  2213.0    4.0       G     DECK    STEEL
102     A       24   1969.0  HIGHWAY   870.0    6.0       G  THROUGH    STEEL
103     O       44   1975.0  HIGHWAY  3756.0    6.0       G  THROUGH    STEEL
104     M        7   1978.0  HIGHWAY   950.0    6.0       G  THROUGH    STEEL

       SPAN REL-L      TYPE
33    SHORT     F  SIMPLE-T
34   MEDIUM     F  SIMPLE-T
35   MEDIUM     F  SIMPLE-T
36   MEDIUM     S  SIMPLE-T
37   MEDIUM     F  SIMPLE-T
..      ...   ...       ...
100  MEDIUM   S-F    CONT-T
101    LONG     F    CONT-T
102  MEDIUM     F      ARCH
103    LONG     F      ARCH
104    LONG     F      ARCH

[72 rows x 12 columns]

In [43]:
old = df2.get_group('Classic')
print(old)

   RIVER LOCATION  ERECTED   PURPOSE  LENGTH  LANES CLEAR-G   T-OR-D MATERIAL  \
0      M        3   1818.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
1      A       25   1819.0   HIGHWAY  1037.0    2.0       N  THROUGH     WOOD
2      A       39   1829.0  AQUEDUCT     NaN    1.0       N  THROUGH     WOOD
3      A       29   1837.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
4      M       23   1838.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
5      A       27   1840.0   HIGHWAY   990.0    2.0       N  THROUGH     WOOD
6      A       28   1844.0  AQUEDUCT  1000.0    1.0       N  THROUGH     IRON
7      M        3   1846.0   HIGHWAY  1500.0    2.0       N  THROUGH     IRON
8      A       39   1848.0  AQUEDUCT     NaN    1.0       N     DECK     WOOD
9      A       29   1851.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD
10     A       39   1853.0        RR     NaN    2.0       N     DECK     WOOD
11     M        6   1856.0   HIGHWAY  1200.0    2.0       N  THROUGH     WOOD
12     A       33   1856.0   HIGHWAY     NaN    2.0       N  THROUGH     WOOD
13     A       28   1857.0        RR     NaN    2.0       N  THROUGH     WOOD
14     A       25   1859.0   HIGHWAY  1030.0    2.0       N  THROUGH     IRON
15     M        4   1863.0        RR  1000.0    2.0       N  THROUGH     IRON
16     A       28   1864.0        RR  1200.0    2.0       N  THROUGH     IRON
17     A       29   1866.0   HIGHWAY  1000.0    2.0       N  THROUGH     WOOD

      SPAN REL-L      TYPE
0    SHORT     S      WOOD
1    SHORT     S      WOOD
2      NaN     S      WOOD
3    SHORT     S      WOOD
4      NaN     S      WOOD
5   MEDIUM     S      WOOD
6    SHORT     S    SUSPEN
7    SHORT     S    SUSPEN
8      NaN     S      WOOD
9   MEDIUM     S      WOOD
10     NaN     S      WOOD
11  MEDIUM     S      WOOD
12     NaN     S      WOOD
13     NaN     S      WOOD
14  MEDIUM   S-F    SUSPEN
15  MEDIUM   NaN  SIMPLE-T
16   SHORT     S  SIMPLE-T
17  MEDIUM     S      WOOD

In [20]:
df['RIVER'].value_counts()

A    47
M    41
O    14
Y     3
Name: RIVER, dtype: int64

In [21]:
print(df.groupby('RIVER')['LENGTH'].median())

RIVER
A    1060.0
M    1325.0
O    1700.0
Y    1240.0
Name: LENGTH, dtype: float64

In [44]:
print(df.groupby('RIVER').size())

RIVER
A    53396.0
M    48672.0
O    23657.0
Y     1240.0
Name: LENGTH, dtype: float64

In [23]:
print(df.groupby('RIVER')['LENGTH'].agg([np.size, np.mean, np.median, np.std]))

       size         mean  median          std
RIVER
A        47  1443.135135  1060.0   725.728606
M        41  1521.000000  1325.0   527.519087
O        14  2150.636364  1700.0  1123.526793
Y         3  1240.000000  1240.0          NaN

In [46]:
df['SPAN'] = df['SPAN'].astype('object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   RIVER     105 non-null    category
 1   LOCATION  104 non-null    category
 2   ERECTED   105 non-null    float64
 3   PURPOSE   105 non-null    category
 4   LENGTH    81 non-null     float64
 5   LANES     92 non-null     float64
 6   CLEAR-G   103 non-null    category
 7   T-OR-D    102 non-null    category
 8   MATERIAL  105 non-null    category
 9   SPAN      92 non-null     object
 10  REL-L     100 non-null    category
 11  TYPE      105 non-null    category
dtypes: category(8), float64(3), object(1)
memory usage: 7.8+ KB

In [48]:
df['SPAN'].fillna('MISSING', inplace=True)

df.head(10)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,M,3,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,A,25,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,MISSING,S,WOOD
3,A,29,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,M,23,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,MISSING,S,WOOD
5,A,27,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,M,3,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,MISSING,S,WOOD
9,A,29,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD

In [77]:
df3 = df.copy()

In [66]:
def length_imputer(series):
    if series.median() < series.mean():
        result = series.median()
    else:
        result = series.mean()
    return series.fillna(result)

df3['LENGTH'] = df3.groupby('RIVER')['LENGTH'].transform(length_imputer)

In [72]:
df3["LENGTH"] = df3.groupby('RIVER').LENGTH.transform(lambda series : series.fillna(series.median() if series.median() < series.mean() else series.mean()))

In [80]:
df3.head(10)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
0,M,3,1818.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,A,25,1819.0,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,A,39,1829.0,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,MISSING,S,WOOD
3,A,29,1837.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,M,23,1838.0,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,MISSING,S,WOOD
5,A,27,1840.0,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,A,28,1844.0,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,M,3,1846.0,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,A,39,1848.0,AQUEDUCT,NaN,1.0,N,DECK,WOOD,MISSING,S,WOOD
9,A,29,1851.0,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD

In [83]:
df3.transform({
    'LENGTH' : lambda series : series.median(),
    'LANES' : lambda item : -1 if not item else item
}, inplace=True)

df3.head(10)

TypeError: Transform function failed

In [85]:
df4 = df3.transform({
    'LENGTH':lambda series : series.fillna(series.median() if series.median() < series.mean() else series.mean()),
    'LANES': lambda item: -1 if pd.isna(item) else item
})

df4.head()

   LENGTH  LANES
0  1300.0    2.0
1  1037.0    2.0
2  1300.0    1.0
3  1000.0    2.0
4  1300.0    2.0